### ISSUE TITLE
web_demo failed to run

### ISSUE THREAD

**Issue by baker915** [QwenLM/Qwen2.5-Omni#23]
I'm trying to run web_demo

after I submmit a request. I got this error:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:0!

My GPU:4500ada * 4

**Comment by wangxiongts** [comment]
We will fix this problem of the transformers code in the near days

**Comment by wangxiongts** [comment]
Hello, we have fixed this bugs, you can pull our docker image again or install the new version of transformers updated in readme.

**Comment by Alex-Songs** [comment]
@wangxiongts The version of transformers specified in the readme has already been installed, but the issue still occurs.
 inputs_embeds = inputs_embeds.masked_scatter(audio_mask, audio_features)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument mask in method wrapper_CUDA__masked_scatter_)

**Comment by Alex-Songs** [comment]
@wangxiongts transformers@f742a644ca32e65758c3adb36225aef1731bd2a8
